package com.financialLab.financedevapp.exception;


public enum ErrorCode {
    BAD_REQUEST, UNAUTHORIZED, GENERIC_ERROR, LOCKED, OBJECT_ALREADY_EXISTS, VALIDATION_ERROR, INTERNAL_SERVER_ERROR, FORBIDDEN, NOT_FOUND, METHOD_NOT_ALLOWED
}
